language: python
sudo: required
dist: xenial
# before_install:
#  - sudo apt-get install -y ghostscript
python:
  - "3.6"

install:
  - pip install -q -r requirements.txt
  - pip install .
script:
  - pytest
  - flake8 quantumflow examples tests tools setup.py
